### PR TITLE
Update to Angular 14 (redux)

### PR DESCRIPTION
**Pull request by oobayly**
This uses the ground work done by @lacroixdavid1 in #271, and also fixes the following:
- failed tests due to dependency conflicts
- consolidate all package versions
- get CircleCI tests to run
- improve test coverage

### CODE REVIEW

**Comment by lacroixdavid1** [comment]
@oobayly great work! Thanks for your help.

**Comment by faraz-ahmad** [comment]
@FERNman  Are you going to merge this PR in near future?

**Comment by FERNman** [comment]
Thanks to everyone who collaborated on this one! I hope to be able to be more active on this repository in the future again, for now, I'm relying on contributors like you 🙂

**Comment by lacroixdavid1** [comment]
@FERNman was this released on NPM?

**Comment by faraz-ahmad** [comment]
I don't think It is released yet. It is still showing last publish 1 year ago.

**Comment by lacroixdavid1** [comment]
Could we have this merged on NPM? Otherwise, all recent contributions are kind of useless.

**Pull request merged**
