### PR TITLE
Angular 15

### PR DESCRIPTION
**Pull request by oobayly**
When I created #278 I [stupidly] targeted Angular 14, which has meant that the package can't be used with Angular 13 - something that's just bitten me in the a**. Also noted in #282

This PR reverts the build version to Angular 12 (v.2.2.2), but updates the peer dependencies to <=15.x (#292)

~Initially, I want to check that this builds correctly on CircleCI~ CircleCI passes now, and I appreciate that releasing a package version that targets a lower Angular version may be problematic.

My next task is to try using this in an angular app starting with 12 to make sure I haven't screwed anything up.
- [x] Install, and run on Angular 12
- [x] Install, and run on Angular 13
- [x] Install, and run on Angular 14
- [x] Install, and run on Angular 15
- [x] Install on Angular 12, and upgrade incrementally to Angular 15

I've also included the following:
- @kussmaul fix in #277
- #297

### CODE REVIEW

**Comment by CarnsJalone** [comment]
Bumping this thread. Is there any momentum to have this pull request reviewed and merged.

**Comment by mlangwell** [comment]
We could really use this PR merged for our team. It is preventing us from completing our update to Angular 15 since we use this package.

**Comment by lazybobcat** [comment]
same here, this is the last package preventing us from updating to Angular 15

**Comment by oobayly** [comment]
For those of you feeling brave, I've attached a zip file of the tarball (GitHub does't support attaching tarballs), from which you can install the branch. This is what I've done with my current project as I really don't want to have to publish an NPM package.

[angular-google-charts-2.2.3.tgz.zip](https://github.com/FERNman/angular-google-charts/files/10941066/angular-google-charts-2.2.3.tgz.zip)

**Comment by HenriqueEichstadt** [comment]
Is there a deadline for approving this pull request?

**Comment by funat** [comment]
Same question here - this library is th only one blocking us to move the project to Angular 15.

**Comment by CristoferEichstadt** [comment]
Is there a deadline for approving this pull request?

**Comment by mohamed-badaoui** [comment]
update to peer dependencies to 16.x ?

**Comment by diegoberges** [comment]
Approves the PR, please.

**Comment by sgovorov** [comment]
Is there a possibility to update dependencies to 16.x?

**Comment by mohamed-badaoui** [comment]
Is there a possibility to update dependencies to 17.x?

**Comment by maurodam** [comment]
Why doesn't anyone maintain this project anymore and approve pull requests?

**Pull request merged**
