### PR TITLE
Updates for ng 13.0.3

### PR DESCRIPTION
**Pull request by schill32**
I was having issues with testing on my local however.  Please verify as well.

Resolves #254 #252

### CODE REVIEW

**Comment by NashIlli** [comment]
+1 
Any update on this?

**Comment by lacroixdavid1** [comment]
Can we have this one merged please?

**Comment by FERNman** [comment]
Hello everybody, sorry for taking so long to respond! Thanks for this PR, I'd be happy to merge it if we get the tests to work 🙂

**Comment by centigrade-julian-lang** [comment]
👀

**Comment by JosephKastier** [comment]
🧐

**Comment by sbaloo9168** [comment]
Yep nice to have

**Comment by lacroixdavid1** [comment]
Should be closed in favor of https://github.com/FERNman/angular-google-charts/pull/271

**Pull request closed without merging**
